services:
  db:
    container_name: onboard-db-dev
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    mem_limit: 4G
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=Changem3
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Changem3 -t 5 -Q "IF DB_ID('master') IS NOT NULL print 'AVAILABLE'" || exit 1
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 10s
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
